
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 04 19:45:06 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LSQPAREN = 15;
  public static final int CONST = 4;
  public static final int CHAR = 13;
  public static final int LSTEQ = 35;
  public static final int RSQPAREN = 16;
  public static final int GRT = 32;
  public static final int NEQUAL = 31;
  public static final int LPAREN = 8;
  public static final int SEMI = 5;
  public static final int CONTINUE = 22;
  public static final int FOR = 43;
  public static final int MINUS = 37;
  public static final int LST = 34;
  public static final int RPAREN = 9;
  public static final int AND = 28;
  public static final int OR = 27;
  public static final int BOOL = 12;
  public static final int COMMA = 6;
  public static final int CLASS = 7;
  public static final int INC = 25;
  public static final int DIV = 39;
  public static final int PLUS = 36;
  public static final int ASSIGN = 41;
  public static final int IF = 20;
  public static final int DOT = 29;
  public static final int ABSTRACT = 19;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int EQUAL = 30;
  public static final int GRTEQ = 33;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int MUL = 38;
  public static final int MODUO = 40;
  public static final int NUMBER = 11;
  public static final int BREAK = 21;
  public static final int IDENT = 14;
  public static final int VOID = 42;
  public static final int ELSE = 44;
  public static final int LBRACE = 10;
  public static final int READ = 24;
  public static final int RBRACE = 3;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int DEC = 26;
  public static final int PRINT = 17;
}

