
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Aug 15 11:28:49 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 50;
  public static final int CONST = 3;
  public static final int MULASSIGN = 44;
  public static final int GRTEQ = 39;
  public static final int GRT = 38;
  public static final int LSTEQ = 41;
  public static final int LPAREN = 25;
  public static final int SEMI = 18;
  public static final int CONTINUE = 9;
  public static final int LST = 40;
  public static final int FOR = 17;
  public static final int MINUS = 30;
  public static final int RPAREN = 26;
  public static final int MODUOASSIGN = 46;
  public static final int AND = 31;
  public static final int DIVASSIGN = 45;
  public static final int OR = 32;
  public static final int BOOL = 49;
  public static final int RSQPAREN = 24;
  public static final int COMMA = 21;
  public static final int CLASS = 4;
  public static final int INC = 27;
  public static final int DIV = 34;
  public static final int PLUS = 29;
  public static final int ASSIGN = 22;
  public static final int IF = 15;
  public static final int DOT = 14;
  public static final int ABSTRACT = 6;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 36;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int NUMBER = 48;
  public static final int IDENT = 47;
  public static final int BREAK = 8;
  public static final int VOID = 7;
  public static final int SUBASSIGN = 43;
  public static final int ADDASSIGN = 42;
  public static final int LBRACE = 19;
  public static final int ELSE = 16;
  public static final int READ = 10;
  public static final int NEQUAL = 37;
  public static final int RBRACE = 20;
  public static final int EXTENDS = 5;
  public static final int PROG = 2;
  public static final int DEC = 28;
  public static final int MODUO = 35;
  public static final int LSQPAREN = 23;
  public static final int PRINT = 11;
}

